# Generated by Django 3.2.10 on 2021-12-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211229_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
