# Generated by Django 3.2.10 on 2022-01-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_social_stackoverflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
