# Generated by Django 3.2.10 on 2021-12-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211221_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to=''),
        ),
    ]
