# Generated by Django 3.2.10 on 2021-12-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sorce_link',
        ),
    ]
